version: "3.9"


services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test-docker
    ports:
      - "5000:8080"
      - "8181:8181"   # WebSocket
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=${DB_HOST};Database=${DB_DATABASE};Username=${DB_USERNAME};Password=${DB_PASSWORD};SSL Mode=VerifyFull;Trust Server Certificate=true

    restart: always
  