# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "production" ]
  pull_request:
    branches: [ "production" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Test
      run: dotnet test WebAPIDocker.Tests/WebAPIDocker.Tests.csproj --configuration Release --verbosity normal

    - name: LoginDocker
      uses: docker/login-action@v2
      with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
          docker build -t chivinh04/demo-hub:latest .
    
    - name: Push Docker image
      run: |
          docker push chivinh04/demo-hub:latest